# Generated by Django 2.2.4 on 2023-07-26 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('StockMaster_app', '0002_auto_20230726_1753'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='StockMaster_app.Prodcut'),
        ),
    ]
